store:
  # data-only container
  image: postgres:latest # reuse postgres container
  volumes:
      - /var/lib/postgresql/data
  command: "true"

postgres:
  image: postgres:latest
  ports:
    - "5432" # random available host port will be chosen, same as -P
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  volumes_from:
    - store # connect postgres and the data-only container
  environment:
    - POSTGRES_PASSWORD=test
    - POSTGRES_DB=Games
      # you can also set the postgres username and database name

go:
  build: .
  links:
    - postgres:db # [other container]:[alias in this container]
    # this will create environment variables in the go container
    # with ip and port info for the postgres container
    # also creates entries in /etc/hosts with ip info
  ports:
    - "3000:3000" # this is port i'm exposing in the container
